version: '3'

services:
  backend:
      build: .
      ports:
        - 8000:8000
      volumes:
        - .:/app
      depends_on:
        - postgresdb
  
  postgresdb:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  